config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: { registrations: 'users/registrations', sessions: 'users/sessions' }

  devise_scope :user do
    get 'users/thanks', to: 'users/registrations#thanks'

    def devise_scope(scope)
      constraint = lambda do |request|
        request.env["devise.mapping"] = Devise.maapings[scope]
        true
      end
      constraints(constraint) do
        yield
      end
    end
  end
  devise_scope :user do
    get 'sign_in', to: "users/sessions#new"
  end
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  root "questions#index"
  resources :questions, only: [:index, :show, :new, :create] do
    collection do
      get 'get_category_children', defaults: { format: 'json' }
      get 'get_category_grandchildren', defaults: { format: 'json' }
      get 'make_resolved'
      get 'search'
    end
    resources :answers, only: [:new, :create, :show, :destroy] do
      resources :likes, only: [:create, :destroy]
    end
  end
  resources :users, only: [:show, :edit, :update]
  resources :subjects, only: [:index] do
    collection do
      get 'search_category'
    end
  end
  

  if Rails.env.development?
    mount LetterOpenerWeb::Engine, at: "/letter_opener"
  end
end

app/models/question.rb
class Question < ApplicationRecord

  validates :title, presence: true
  validates :question, presence: true

  belongs_to :user
  belongs_to :subject
  has_many :answers

  def self.search(keyword)
    Question.where('title LIKE ?', "%#{keyword}")
  end
end

app/controllers/questions_controller.rb
class QuestionsController < ApplicationController
  before_action :authenticate_user!, only: [:new, :create, :show]
  def index
    @questions = Question.all.order(created_at: "DESC").page(params[:page]).per(7)
    respond_to do |format|
      format.html
      format.js
    end
  end

  def search
    @questions = Question.search(params[:keyword]).order(created_at: "DESC").page(params[:page]).per(7)
    @keyword = params[:keyword]
    if @keyword.empty?
      redirect_to questions_path
    else
      //
    end
  end

  def new
    @question = Question.new
    @category_parent_array = Subject.where(ancestry: nil)
  end

  def create
    @question = Question.new(question_params)
    @users = User.all
    if @question.save
      @users.each do |user|
        if user.notice && current_user.id != @question.user.id
          NoticeMailer.posted_question(user, current_user, @question).deliver
        end
      end
    else
      @category_parent_array = Subject.where(ancestry: nil)
      render :new
    end
  end

  def get_category_children
    @category_children = Subject.find_by(id: "#{params[:parent_id]}", ancestry: nil).children
  end

  def get_category_grandchildren
    @category_grandchildren = Subject.find("#{params[:child_id]}").children
  end

  def show
    @question = Question.find(params[:id])
    @answer = Answer.new
    @answers = @question.answers.order(created_at: "DESC")
  end

  def make_resolved
    @question = Question.find(params[:id])
    if @question.update(is_solved: true)
      //
    end
    respond_to do |format|
      format.html { render :show }
      format.js
    end
  end

  private
  def question_params
    if params[:grandchild_id].present?
      params[:question][:subject_id] = params[:grandchild_id]
    elsif params[:child_id].present?
      params[:question][:subject_id] = params[:child_id]  
    else  
    end
    params.require(:question).permit(:title, :question, :subject_id).merge(user_id: current_user.id)
  end
end

app/helpers/questions_helper.rb
module QuestionsHelper
end

app/views/questions/_answer_input.html.haml
- if question.is_solved?
  .AnswerForm.Wrapper
    %p.AnswerForm__head Already Solved
- else
  .AnswerForm.Wrapper
    %p.AnswerForm__head Send an Answer
    = form_with model: answer, url: question_answers_path(question.id), class: "AnswerForm__form", local: true do |f|
      .AnswerForm__textarea
        = f.text_area :answer, { class: "AnswerTextarea AnswerForm__textarea_defaultnone", placeholder: "Type a message", cols: "70", rows: "10" }
      .AnswerForm__submit
        = f.submit "Send", { class:"Button AnswerSend" }

app/views/questions/_answer_room.html.haml
- if answers
  - answers.each do |answer|
    .AnswerList
      .AnswerInfo
        .AnswerInfo__time
          = "#{time_ago_in_words(answer.created_at)}前"
        .AnswerInfo__username
          = answer.user.name
        .AnswerInfo__user
          = image_tag answer.user.image.url, class: "UserIcon__icon_style small_pic"
      .AnswerList__answer
        = answer.answer

app/views/questions/_header.html.haml
.Header
  .TitleBox
    %p.TitleBox__maintext StudyShare
    %p.TitleBox__subtext すぐ答えてに応える
  .AccountButton
    - if (user_signed_in?)
    - else
      = link_to "新規登録", new_user_registration_path, { class: "btn btn-info AccountButton__signin"}
        
      
      = link_to "サインイン", new_user_session_path, { class: "btn btn-info AccountButton__login"}

    
    

app/views/questions/_is_solved.html.haml
- if question.is_solved?
  .solved
    = "解決済み"
- else
  = link_to( '受付中',  make_resolved_questions_path(id: question.id), remote: true, class: "resolvebutton", id: "Button")
 

app/views/questions/_main.html.haml
.SearchCenter
  - if user_signed_in?
    = form_with url: search_questions_path, method: :get, local: true do |f|
      .SearchBox
        = f.text_field :keyword, class: "SearchBox__form", placeholder: "keyword"
        = f.submit "Search", class: "SearchBox__submit"
.Main
  .QuestionBoxes
    = render partial: 'question'

app/views/questions/_question.html.haml
- @questions.each do |question|
  .QuestionBox
    .UserIcon
      = link_to user_path(question.user.id), class: "UserIcon__icon" do
        - if(question.user.image.present?)
          .UserIcon__icon_style
            = image_tag question.user.image.url, class:"UserIcon__icon_style"
        - else
          = image_tag "/images/default.jpg", class: "UserIcon__icon_style"
        %p.UserIcon__name
          = question.user.name
    .InfoBox
      .TitleStatus
        .InfoBox__title
          = link_to question_path(question.id) do
            = question.title
        .TitleStatus__astatus
          %span.TitleStatus__acount= "回答数:#{question.answers.count}件"
          - if question.is_solved?
            %span.TitleStatus__solved 解決済
          - else
            %spna.TitleStatus__unsolved 受付中
      .SubInfoBox
        %ul.SubInfoBox__tag
          %li.Tag-item
            - if question.subject.has_parent?
              - if question.subject.parent.has_parent?
                = question.subject.parent.parent.category
                %li.Tag-item
                  = question.subject.parent.category
                %li.Tag-item
                  = question.subject.category
              - else
                = question.subject.parent.category
                %li.Tag-item
                  = question.subject.category
            - else
              = question.subject.category
        .SubInfoBox__post-date
          = "#{time_ago_in_words(question.created_at)}前"
.PageBox
  = paginate @questions, remote: true

app/views/questions/create.html.haml
.Content
  .QuestionFormBox
    %h2 投稿が完了しました。

    = link_to 'メイン画面に戻る', root_path

app/views/questions/index.html.haml
= render 'header'
.wrapper
  = render 'main'

app/views/questions/index.js.erb
$('.QuestionBoxes').html("<%= j(render :partial => 'question') %>");

app/views/questions/make_resolved.js.erb
$("#resolved").children().remove();
$(".AnswerForm").children().remove();
let p = document.createElement("p");
p.innerHTML = "Already Solved";
p.classList.add("AnswerForm__head");
$(".AnswerForm").append(p);

$("#resolved").append('<%= escape_javascript render  :partial => "is_solved" ,locals: {question: @question},:layout => false %>');

app/views/questions/new.html.haml
.Content
  .QuestionFormBox
    = form_with model: @question, url: questions_path, local: true, class: "QuestionForm" do |f|
      = render "/devise/shared/error_messages", {resource: @question, attribute: :title}
      .QuestionTitle
        .QuestionTitle__label
          = f.label 'タイトル'
          %span (必須)
        = f.text_field :title, autofocus: true
      = render "/devise/shared/error_messages", {resource: @question, attribute: :question}
      .QuestionText
        .QuestionText__label
          = f.label '本文'
          %span (必須)
        .QuestionText__modifier
          %span= icon('fas', 'highlighter')
          %span= icon('fas', 'bold')
          %span= icon('fas', 'link')
        = f.text_area :question, rows: 15
      .QuestionCategory
        .QuestionCategory__label
          = f.label 'カテゴリー'
          %span (任意)
        .QuestionCategory__category.ChoiceBox.Questionwrapper
          = f.collection_select :subject_id, @category_parent_array, :id, :category, {}, {class: "ChoiceBox__input"}
        = f.submit "質問を投稿する", class: "QuestionSubmit"

app/views/questions/search.html.haml
.searchwrapper
  .Main
    .QuestionBoxes
      .Dummy
      - if @questions.count > 0
        .SearchResult
          %p.SearchResult__finded= "検索条件: 「#{@keyword}」"
      - else
        .SearchResult
          %p.SearchResult__notfinded= "#{@keyword} の検索結果はありませんでした。"
      = render partial: 'question'
    

app/views/questions/show.html.haml
.QandAwrapper
  .QandAwrapper__topfield
    .ShowQuestion.Wrapper
      %p.ShowQuestion__head Question
      .ShowQuestion__title
        = @question.title
        %span#resolved
          = render partial: 'is_solved', locals: { question: @question }
      .ShowQuestion__text.Showtext
        = @question.question
      .ShowQuestion__category
        %span カテゴリー:
        .Showcategory
          %ul.SubInfoBox__tag
            %li.Tag-item
              - if @question.subject.has_parent?
                - if @question.subject.parent.has_parent?
                  = @question.subject.parent.parent.category
                  %li.Tag-item
                    = @question.subject.parent.category
                  %li.Tag-item
                    = @question.subject.category
                - else
                  = @question.subject.parent.category
                  %li.Tag-item
                    = @question.subject.category
              - else
                = @question.subject.category
  .QandAwrapper__bottom
    = render partial: 'answer_input', locals: { question: @question, answer: @answer }
    .AnswerLists.Wrapper
      .AnswerLists__sum
        %h3 解答ルーム
      .AnswerLists__box
        = render partial: 'answer_room', locals: { answers: @answers }