config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: { registrations: 'users/registrations', sessions: 'users/sessions' }

  devise_scope :user do
    get 'users/thanks', to: 'users/registrations#thanks'

    def devise_scope(scope)
      constraint = lambda do |request|
        request.env["devise.mapping"] = Devise.maapings[scope]
        true
      end
      constraints(constraint) do
        yield
      end
    end
  end
  devise_scope :user do
    get 'sign_in', to: "users/sessions#new"
  end
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  root "questions#index"
  resources :questions, only: [:index, :show, :new, :create] do
    collection do
      get 'get_category_children', defaults: { format: 'json' }
      get 'get_category_grandchildren', defaults: { format: 'json' }
      get 'make_resolved'
      get 'search'
    end
    resources :answers, only: [:new, :create, :show, :destroy] do
      resources :likes, only: [:create, :destroy]
    end
  end
  resources :users, only: [:show, :edit, :update]
  resources :subjects, only: [:index] do
    collection do
      get 'search_category'
    end
  end
  

  if Rails.env.development?
    mount LetterOpenerWeb::Engine, at: "/letter_opener"
  end
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  validates :name, presence: true, uniqueness: true
  validates :birth_date, presence: true
  validates :job, presence: true
  validate :job_not_default

  has_many :questions
  has_many :answers
  has_many :likes, dependent: :destroy

  def job_not_default
    if job.present? && (job == "職業を選んでください")
      errors.add(:job, "を入力してください")
    end
  end

  def already_liked?(answer)
    self.likes.exitst?(answer_id: answer.id)
  end

  enum job_select: {
      "職業を選んでください": "職業を選んでください",
      "中学生": "中学生",
      "高校生": "高校生",
      "大学生": "大学生",
      "その他": "その他"
  }, _prefix: true

  mount_uploader :image, ImagesUploader
end

app/controllers/users/confirmations_controller.rb
# frozen_string_literal: true

class Users::ConfirmationsController < Devise::ConfirmationsController
  # GET /resource/confirmation/new
  # def new
  #   super
  # end

  # POST /resource/confirmation
  # def create
  #   super
  # end

  # GET /resource/confirmation?confirmation_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after resending confirmation instructions.
  # def after_resending_confirmation_instructions_path_for(resource_name)
  #   super(resource_name)
  # end

  # The path used after confirmation.
  # def after_confirmation_path_for(resource_name, resource)
  #   super(resource_name, resource)
  # end
end

app/controllers/users/omniauth_callbacks_controller.rb
# frozen_string_literal: true

class Users::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  # You should configure your model like this:
  # devise :omniauthable, omniauth_providers: [:twitter]

  # You should also create an action method in this controller like this:
  # def twitter
  # end

  # More info at:
  # https://github.com/heartcombo/devise#omniauth

  # GET|POST /resource/auth/twitter
  # def passthru
  #   super
  # end

  # GET|POST /users/auth/twitter/callback
  # def failure
  #   super
  # end

  # protected

  # The path used when OmniAuth fails
  # def after_omniauth_failure_path_for(scope)
  #   super(scope)
  # end
end

app/controllers/users/passwords_controller.rb
# frozen_string_literal: true

class Users::PasswordsController < Devise::PasswordsController
  # GET /resource/password/new
  # def new
  #   super
  # end

  # POST /resource/password
  # def create
  #   super
  # end

  # GET /resource/password/edit?reset_password_token=abcdef
  # def edit
  #   super
  # end

  # PUT /resource/password
  # def update
  #   super
  # end

  # protected

  # def after_resetting_password_path_for(resource)
  #   super(resource)
  # end

  # The path used after sending reset password instructions
  # def after_sending_reset_password_instructions_path_for(resource_name)
  #   super(resource_name)
  # end
end

app/controllers/users/registrations_controller.rb
# frozen_string_literal: true

class Users::RegistrationsController < Devise::RegistrationsController
  before_action :configure_sign_up_params, only: [:create]
  before_action :configure_account_update_params, only: [:update]

  # GET /resource/sign_up
  def new
    @signup = true
    super
  end

  # POST /resource
  # def create
  #   super
  # end

  # GET /resource/edit
  # def edit
  #   super
  # end

  # PUT /resource
  # def update
  #   super
  # end

  # DELETE /resource
  # def destroy
  #   super
  # end

  # GET /resource/cancel
  # Forces the session data which is usually expired after sign
  # in to be expired now. This is useful if the user wants to
  # cancel oauth signing in/up in the middle of the process,
  # removing all OAuth session data.
  # def cancel
  #   super
  # end

  def thanks
  end

  protected

  # If you have extra params to permit, append them to the sanitizer.
  def configure_sign_up_params
    devise_parameter_sanitizer.permit(:sign_up, keys: [:name, :birth_date, :job])
  end

  # If you have extra params to permit, append them to the sanitizer.
  def configure_account_update_params
    devise_parameter_sanitizer.permit(:account_update, keys: [:name, :job, :image])
  end

  # The path used after sign up.
  def after_sign_up_path_for(resource)
    users_thanks_path
  end

  def after_update_path_for(resource)
    edit_user_registration_path
  end

  # The path used after sign up for inactive accounts.
  # def after_inactive_sign_up_path_for(resource)
  #   users_thanks_path
  # end
end

app/controllers/users/sessions_controller.rb
# frozen_string_literal: true

class Users::SessionsController < Devise::SessionsController
  # before_action :configure_sign_in_params, only: [:create]

  # GET /resource/sign_in
  def new
    super
  end

  # POST /resource/sign_in
  def create
    super
    email = User.where('email LIKE ?', params[:email] )
    password = User.where('passowrd LIKE ?', params[:password])
    if email && password
      flash[:notice] = 'ログインに成功しました。'
    else
      flash[:alert] = "メールアドレスまたはパスワードが一致しません" 
    end
    
  end

  # DELETE /resource/sign_out
  # def destroy
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_in_params
  #   devise_parameter_sanitizer.permit(:sign_in, keys: [:attribute])
  # end
end

app/controllers/users/unlocks_controller.rb
# frozen_string_literal: true

class Users::UnlocksController < Devise::UnlocksController
  # GET /resource/unlock/new
  # def new
  #   super
  # end

  # POST /resource/unlock
  # def create
  #   super
  # end

  # GET /resource/unlock?unlock_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after sending unlock password instructions
  # def after_sending_unlock_instructions_path_for(resource)
  #   super(resource)
  # end

  # The path used after unlocking the resource
  # def after_unlock_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :get_user, only: [:edit, :update, :show]
  before_action :authenticate_user!, only: [:edit, :update]

  def edit
    render :show unless current_user.id == @user.id
  end

  def update
    if @user.update(user_params)
      redirect_to root_path
    else
      render :edit
    end
  end

  def destroy
  end

  def show
    @user_questions = Question.where(user_id: params[:id])
    @user_answers = Answer.where(user_id: params[:id])
  end

  private
  def user_params
    params.require(:user).permit(:name, :job, :image, :email, :notice)
  end

  def get_user
    @user = User.find(params[:id])
  end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/_user_info.html.haml
.ShowAccount__leftfield
  .InfoField
    .fas.fa-user
    %p.InfoField__list= user.name
  .InfoField
    - if user_signed_in? && current_user.id == user.id
      .fas.fa-envelope
      %p.InfoField__list= user.email
  .InfoField
    .fas.fa-graduation-cap
    %p.InfoField__list= user.job
  .InfoField
    .fas.fa-paper-plane
    - if user.notice
      %p.InfoField__list= "Get Notice"
    - else
      %p.InfoField__list= "Not Get Notice"
.ShowAccount__rightfield
  - if @user.image?
    .ImageInfo
      = image_tag @user.image.url, class: "ImageInfo__image"
  - else
    .ImageInfo
      = image_tag "/images/default.jpg", class: "ImageInfo__image"
  - if user_signed_in? && @user.id == current_user.id
    = link_to "Edit", edit_user_path(@user.id), { class: "Button ShowAccount__submit"}

app/views/users/_user_qanda.html.haml
%input.QandALists__input{type: "radio", name:"tabset", id:"question-tab"}
  %label.QandALists__tab{for: "question-tab"}= "Questions ▼"
.QandALists__content#question-content-tab
  %ul.QandALists__lists
    - if user_questions.present?
      - user_questions.each do |question|
        %li.QandALists__item
          = "title: "
          = link_to "#{question.title}", question_path(question.id), class: "User_Questions__link"
    - else
      %p.QandALists_none= "#{current_user.name}様が投稿した質問はありません。"
%input.QandALists__input{type: "radio", name:"tabset", id:"answer-tab"}
  %label.QandALists__tab{for: "answer-tab"}= "Answers ▼"
.QandALists__content#answer-content-tab
  %ul.QandALists__lists
    - if user_answers.present?
      - user_answers.each do |answer|
        %li.QandALists__item
          = "title: "
          = link_to "#{answer.question.title}", question_path(answer.question.id), class: "User_Answers__link"
    - else
      %p.QandALists_none= "#{current_user.name}様が投稿した回答はありません。"

app/views/users/edit.html.haml
.Content
  .Content__wrapper
    .Title
      %h2 Edit Account
    = form_with model: @user, url: user_path(@user.id), method: :patch, local: true, class: "ShowAccount" do |f|
      .ShowAccount__leftfield
        = render "/devise/shared/error_messages", {resource: @user, attribute: :name}
        .InfoField
          .fas.fa-user
          = f.text_field :name, autofocus: true, class: 'InfoField__list', value: @user.name
        = render "/devise/shared/error_messages", {resource: @user, attribute: :email}
        .InfoField
          .fas.fa-envelope
          = f.email_field :email, value: @user.email, class: 'InfoField__list'
        = render "/devise/shared/error_messages", {resource: @user, attribute: :job}
        .InfoField
          .fas.fa-graduation-cap
          = f.select :job, options_for_select(User.job_selects, selected: @user.job), {}, class: 'InfoField__list'
        .InfoField
          .fas.fa-paper-plane
          .CheckBox
            = f.label "Get Notice", class: "InfoField__list"
            = f.check_box :notice
      .ShowAccount__rightfield
        = f.label :image, class: 'ImageInfo mg-t' do
          - if @user.image?
            = image_tag @user.image.url, class: "ImageInfo__image"
            = f.file_field :image, class: 'ImageInfo__upload'
          - else
            = image_tag "/images/default.jpg", class: "ImageInfo__image"
            = f.file_field :image, class: 'ImageInfo__upload'
        = f.submit "Change", class: "Button block"

app/views/users/show.html.haml
.Content
  .Content__wrapper
    .Title
      %h2 Account Information
    .ShowAccount
      = render partial: 'user_info', locals: { user: @user }
  - if user_signed_in? && current_user.id == @user.id
    .Content__bottom.QandALists
      = render partial: 'user_qanda', locals: { user_questions: @user_questions, user_answers: @user_answers }