config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: { registrations: 'users/registrations', sessions: 'users/sessions' }

  devise_scope :user do
    get 'users/thanks', to: 'users/registrations#thanks'

    def devise_scope(scope)
      constraint = lambda do |request|
        request.env["devise.mapping"] = Devise.maapings[scope]
        true
      end
      constraints(constraint) do
        yield
      end
    end
  end
  devise_scope :user do
    get 'sign_in', to: "users/sessions#new"
  end
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  root "questions#index"
  resources :questions, only: [:index, :show, :new, :create] do
    collection do
      get 'get_category_children', defaults: { format: 'json' }
      get 'get_category_grandchildren', defaults: { format: 'json' }
      get 'make_resolved'
      get 'search'
    end
    resources :answers, only: [:new, :create, :show, :destroy] do
      resources :likes, only: [:create, :destroy]
    end
  end
  resources :users, only: [:show, :edit, :update]
  resources :subjects, only: [:index] do
    collection do
      get 'search_category'
    end
  end
  

  if Rails.env.development?
    mount LetterOpenerWeb::Engine, at: "/letter_opener"
  end
end

app/views/modules/_footer.html.haml
.Footer
  .Footer__text
    2020 CopyRights

app/views/modules/_nav.html.haml
%nav.navbar.navbar-expand-lg.navbar-light.navcolor.fixed-top
  %a.navbar-brand.text-decoration-none.text-white.deg-action{ href: "/" } 
    = icon('fas', 'school')
    &nbsp;StudyShare
  #Menu_bar.Menu_bar
    %span.Menu_bar__item
    %span.Menu_bar__item
    %span.Menu_bar__item
  .Menu.hidden
    %ul.navbar-nav.mr-auto
      - if user_signed_in?
        %li.nav-item.active.border-right.border-left.ml-5.font-weight-bold.nav-font
          = link_to "Question", new_question_path(current_user.id), class: "nav-link text-white deg-action"
      %li.nav-item.active.border-right.border-left.ml-5.font-weight-bold.nav-font
        = link_to "Category", subjects_path, class: "nav-link text-white deg-action"
    - if (user_signed_in?)
      %li.nav-item.active.ml-3.font-weight-bold.nav-link.text-white.float-right.show
        = "#{current_user.name}さん,こんにちは！"
    %ul.navbar-nav
      - if (user_signed_in?)
        %li.nav-item.active.border-right.border-left.ml-3.font-weight-bold
          = link_to "User", user_path(current_user.id), class: "nav-link text-white deg-action"
        %li.nav-item.active.border-right.border-left.ml-3.font-weight-bold
          = link_to "Log out", destroy_user_session_path, method: :delete, class: "nav-link text-white deg-action"
      
      - else
        %li.nav-item.active.border-right.border-left.ml-3.font-weight-bold
          = link_to "Sign In", new_user_session_path, { class: "nav-link text-white deg-action"}

        %li.nav-item.active.border-right.border-left.ml-3.font-weight-bold
          = link_to "Sign Up", new_user_registration_path, { class: "nav-link text-white deg-action"}
   