config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: { registrations: 'users/registrations', sessions: 'users/sessions' }

  devise_scope :user do
    get 'users/thanks', to: 'users/registrations#thanks'

    def devise_scope(scope)
      constraint = lambda do |request|
        request.env["devise.mapping"] = Devise.maapings[scope]
        true
      end
      constraints(constraint) do
        yield
      end
    end
  end
  devise_scope :user do
    get 'sign_in', to: "users/sessions#new"
  end
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  root "questions#index"
  resources :questions, only: [:index, :show, :new, :create] do
    collection do
      get 'get_category_children', defaults: { format: 'json' }
      get 'get_category_grandchildren', defaults: { format: 'json' }
      get 'make_resolved'
      get 'search'
    end
    resources :answers, only: [:new, :create, :show, :destroy] do
      resources :likes, only: [:create, :destroy]
    end
  end
  resources :users, only: [:show, :edit, :update]
  resources :subjects, only: [:index] do
    collection do
      get 'search_category'
    end
  end
  

  if Rails.env.development?
    mount LetterOpenerWeb::Engine, at: "/letter_opener"
  end
end

app/models/subject.rb
class Subject < ApplicationRecord
  has_many :questions
  has_ancestry
end

app/controllers/subjects_controller.rb
class SubjectsController < ApplicationController
  def index
    parent_subs = Subject.where(ancestry: nil).where.not(category: "カテゴリーなし")
    @subjects = []
    find_category(parent_subs)
  end

  def search_category
    subject = Subject.find_by(category: params[:category])
    first_category_ids = subject.child_ids
    @questions = Question.where(subject_id: first_category_ids).order(created_at: "DESC").page(params[:page]).per(7)
    @keyword = params[:category]
  end

  private
  def find_category(lists)
    lists.each do |subject|
      hash = {}
      child_lists = []
      parent_cat = subject.category
      subject.children.each do |child|
        child_cat = child.category
        child_lists << child_cat
      end
      hash[parent_cat] = child_lists
      @subjects << hash
    end
  end
end

app/helpers/subjects_helper.rb
module SubjectsHelper
end

app/views/subjects/index.html.haml
.Content
  %h2.Content__header Categories
  .Content__bottom.CategoryTab
    - @subjects.each_with_index do |subject, index|
      %input.CategoryTab__input{type: "radio", name:"tabset", id:"category-#{index}"}
        %label.CategoryTab__tab{for: "category-#{index}"}= "#{subject.key(subject.values.flatten)} ▼"
      .CategoryTab__content{id: "category-content-#{index}"}
        %ul.CategoryTab__lists.Card
          - subject.values.flatten.each do |child|
            %li.CategoryTabs__item
              = form_with url: search_category_subjects_path, method: :get, local: true, class: "FormCard" do |f|
                = f.hidden_field :category, value: child, class: "FormCard__hidden"
                .FormCard__wrap
                  = f.submit "#{child}", { class: "FormCard__link" }

app/views/subjects/search_category.html.haml
.searchwrapper
  .Main
    .QuestionBoxes
      .Dummy
      - if @questions.count > 0
        .SearchResult
          %p.SearchResult__finded= "カテゴリー: 「#{@keyword}」"
      - else
        .SearchResult
          %p.SearchResult__notfinded= "#{@keyword} の質問は現在投稿されていません。"
      = render partial: 'questions/question'
    